### ISSUE TITLE
how to get a nominator's rank in it's validator list of nominators?

### ISSUE THREAD

**Issue by p4tpr0** [subscan-explorer/subscan-api-docs#20]
Hello,
Getting reward from Polkadot staking is highly dependent on ones rank in the list of nominators of ones current validator.
If I'm often ranked lower than 250th it's important to be able to notice in order to change validators. 
I can't find an API call that would return the current rank of a nominator's address inside the list of all nominators addresses of the current validator. Is it possible to get this info or to derive this info from different API requests?

**Comment by freehere107** [comment]
https://support.subscan.io/#nominators this API maybe can help you

**Comment by p4tpr0** [comment]
Thanks! I've finally managed to get some result, but it's quite convoluted:
- one call to api/scan/staking/voted to get the validator address
- N calls to api/scan/staking/nominators to get the record where my nominator address is ranked

The nominator's rank info would be really nice to have in the result of api/scan/staking/voted

**Comment by freehere107** [comment]
@p4tpr0 great, will notify you if `api/scan/staking/voted` is an update
